Repository shawshankkumar/hackout-travelmate, pull requests merged in 2023-11, with the labels that each got.

#11 Add axios dependency and implement Google
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/api/auth/controller.ts
  backend/src/api/auth/models.ts
  backend/src/api/auth/routes.ts
  backend/src/api/user/controller.ts
  backend/src/api/user/models.ts
  backend/src/api/user/routes.ts
  backend/src/utils/auth/google-auth.ts
  backend/src/utils/config.ts
  backend/src/utils/middlewares/tokenVerify.ts
Labels: work-in-progress

#13 username page init
  web/next.config.js
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/ComboBox.tsx
  web/src/components/CompanyLogo.tsx
  web/src/components/DashboardSidebar.tsx
  web/src/components/GetSection.tsx
  web/src/components/ProfileBar.tsx
  web/src/components/ServiceCard.tsx
  web/src/components/TimeSlotPicker.tsx
  web/src/components/ui/popover.tsx
  web/src/pages/[username].tsx
  web/src/pages/[username]/[service].tsx
  web/src/pages/dashboard/[section].tsx
  web/src/utils/constants.ts
Labels: work-in-progress

#26 refactor: use auth
  web/src/components/Navbar.tsx
  web/src/components/ProfileBar.tsx
  web/src/hooks/use-auth.ts
  web/src/hooks/use-user.ts
  web/src/pages/auth.tsx
  web/src/pages/dashboard.tsx
  web/src/pages/oauth-callback.tsx
Labels: enhancement, frontend

#29 fix: auth ui
  web/src/pages/auth.tsx
Labels: enhancement, frontend

#27 feat: time picker ui
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/TimeSlotPicker.tsx
  web/src/components/ui/scroll-area.tsx
  web/src/pages/[username]/[service].tsx
Labels: enhancement, frontend, do not merge

#31 Refactor UI layout and improve time slot picker
  web/public/images/masonry.png
  web/src/components/Logo.tsx
  web/src/components/TimeSlotPicker.tsx
  web/src/components/sections/Hero.tsx
  web/src/pages/[username]/[service].tsx
  web/src/pages/[username]/index.tsx
  web/src/pages/_app.tsx
  web/src/pages/auth.tsx
Labels: work-in-progress, frontend

#33 Add removeToken function to useStoreZ and call it
  web/src/hooks/use-user.ts
  web/src/utils/state/auth.ts
Labels: enhancement

#34 feat: booking confirmation ticket
  web/src/components/TimeSlotPicker.tsx
  web/src/pages/[username]/[service].tsx
  web/src/styles/globals.css
  web/tailwind.config.ts
Labels: enhancement, frontend

#40 Implement about page
  web/public/images/CreatePageTemplate.svg
  web/src/components/sections/About.tsx
  web/src/components/sections/Hero.tsx
  web/src/pages/index.tsx
  web/tailwind.config.ts
Labels: enhancement

#41 feat: confirmation flow
  web/src/components/TimeSlotPicker.tsx
  web/src/hooks/use-user.ts
  web/src/pages/[username]/[service].tsx
  web/src/pages/oauth-callback.tsx
  web/src/types/index.ts
  web/tailwind.config.ts
Labels: enhancement, frontend

#42 Profile/feat/hs
  web/package.json
  web/pnpm-lock.yaml
  web/src/components/Booking.tsx
  web/src/components/Calendar.tsx
  web/src/components/DashboardSidebar.tsx
  web/src/components/GetSection.tsx
  web/src/components/Profile.tsx
  web/src/components/ProfileBar.tsx
  web/src/components/ServiceCard.tsx
  web/src/components/Services.tsx
  web/src/components/ui/checkbox.tsx
  web/src/components/ui/input.tsx
  web/src/components/ui/label.tsx
  web/src/components/ui/select.tsx
  web/src/components/ui/textarea.tsx
  web/src/hooks/use-user.ts
  web/src/pages/[username]/index.tsx
  web/src/styles/globals.css
  web/src/types/index.ts
  web/src/utils/constants.ts
Labels: work-in-progress

#43 Landing page
  web/public/images/feature1.svg
  web/public/images/feature2.svg
  web/public/images/feature3.svg
  web/public/images/feature4.svg
  web/public/images/feature5.svg
  web/public/images/logoIcon.svg
  web/src/components/Footer.tsx
  web/src/components/sections/Features.tsx
  web/src/components/sections/QnA.tsx
  web/src/pages/_app.tsx
  web/src/pages/index.tsx
  web/tailwind.config.ts
Labels: enhancement, frontend

#50 fix: footer image
  web/public/images/Logo.svg
  web/src/components/Footer.tsx
Labels: bug, frontend

#51 Add mailer utility and resend package
  backend/package.json
  backend/pnpm-lock.yaml
  backend/src/api/user/controller.ts
  backend/src/api/user/models.ts
  backend/src/utils/config.ts
  backend/src/utils/mailer.ts
Labels: work-in-progress

#52 feat: post after booking
  web/src/hooks/use-user.ts
  web/src/pages/[username]/[service].tsx
  web/src/utils/api.ts
Labels: enhancement, frontend

#54 feat: link logo to home
  web/src/components/DashboardSidebar.tsx
Labels: enhancement, frontend
